run:
    skip-dirs:
        - vendor

linters:
    enable-all: true
    disable:
        - funlen
        - interfacer
        - maligned
        - errcheck
        - gochecknoglobals
        - gomnd
        - dupl
        - exhaustivestruct
        - varnamelen
        - forcetypeassert
        - exhaustruct
        - ifshort
        - paralleltest
        - goerr113
        - wsl
        - gci
        - wrapcheck
        - errorlint
        - cyclop

        # Drives todos nuts
        - godox

issues:
  exclude-rules:
    - linters:
        - lll
        - gocognit
        - staticcheck
        - scopelint
      path: "(.+)_test.go|mock.go"
