-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 11:03:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ports` DEFAULT CHARACTER SET utf8 ;
USE `ports` ;

-- -----------------------------------------------------
-- Table `ports`.`port`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ports`.`port` (
  `unloc` VARCHAR(10) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `alias` JSON NULL,
  `regions` JSON NULL,
  `latitude` DECIMAL(11,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `province` VARCHAR(255) NOT NULL,
  `timezone` VARCHAR(255) NOT NULL,
  `code` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`unloc`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
